Add libX11 to librviz target_link_libraries (#1023)
* Add libX11 to librviz target_link_libraries

Required by ogre_helpers/render_system.cpp:
render_system.cpp: undefined reference to `XOpenDisplay'
render_system.cpp: undefined reference to `XCreateSimpleWindow'

* Don't search for X11 on Apple devices